### ISSUE TITLE
Metal box seems to be either missing or incredbly rare

### ISSUE THREAD

**Issue by PejmanHaghgou** [Jods-Its/Jods-Indoors-Greenery#1]
I have found over 100 electronic parts
a dozen of meshes
but I havnt seen a single Metal box.

I thought it was the metal containers from vanilla that we could pickup but it doesn't seem to be the case

**Comment by Jods-Its** [comment]
> I have found over 100 electronic parts a dozen of meshes but I havnt seen a single Metal box.
> 
> I thought it was the metal containers from vanilla that we could pickup but it doesn't seem to be the case

You have to craft it in a forge
